# Generated by Django 4.2.7 on 2026-01-22 17:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Bill title/description", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of services"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be paid",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the bill",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(help_text="Date when bill was issued")),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="Date when bill was fully paid", null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("insurance", "Insurance"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        help_text="Method of payment",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, help_text="Transaction/Reference ID", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Staff/Admin who created this bill",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this bill belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                ("payment_date", models.DateField(help_text="Date of payment")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("insurance", "Insurance"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, help_text="Transaction/Reference ID", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Payment notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Bill this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.bill",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Staff who recorded this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["patient", "status"], name="billing_bil_patient_fd105b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["due_date"], name="billing_bil_due_dat_18c2c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="billing_bil_status_ddee07_idx"),
        ),
    ]
