# Generated by Django 4.2.7 on 2026-01-22 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient (user) this bill belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
