# Generated by Django 4.2.7 on 2026-01-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelehealthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration",
                    models.IntegerField(default=30, help_text="Duration in minutes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "session_url",
                    models.URLField(blank=True, help_text="Video call URL", null=True),
                ),
                (
                    "room_id",
                    models.CharField(
                        blank=True, help_text="Video room ID", max_length=255, null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Session notes", null=True),
                ),
                ("has_recording", models.BooleanField(default=False)),
                ("has_transcript", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("transcript_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "telehealth_session",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="telehealth__patient_53367d_idx",
                    ),
                    models.Index(
                        fields=["therapist", "status"],
                        name="telehealth__therapi_ebc278_idx",
                    ),
                    models.Index(
                        fields=["scheduled_at"], name="telehealth__schedul_3b2421_idx"
                    ),
                ],
            },
        ),
    ]
