# Generated by Django 4.2.7 on 2026-01-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telehealth", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            # Add columns if they don't exist
            sql="""
            -- Add id column if not exists (UUID primary key)
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='id') THEN
                    ALTER TABLE telehealth_session ADD COLUMN id UUID DEFAULT gen_random_uuid() PRIMARY KEY;
                END IF;
            END $$;

            -- Add title column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='title') THEN
                    ALTER TABLE telehealth_session ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT '';
                END IF;
            END $$;

            -- Add description column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='description') THEN
                    ALTER TABLE telehealth_session ADD COLUMN description TEXT NULL;
                END IF;
            END $$;

            -- Add patient_id column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='patient_id') THEN
                    ALTER TABLE telehealth_session ADD COLUMN patient_id UUID NOT NULL;
                    ALTER TABLE telehealth_session ADD CONSTRAINT telehealth_session_patient_id_fk 
                        FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE;
                END IF;
            END $$;

            -- Add therapist_id column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='therapist_id') THEN
                    ALTER TABLE telehealth_session ADD COLUMN therapist_id UUID NOT NULL;
                    ALTER TABLE telehealth_session ADD CONSTRAINT telehealth_session_therapist_id_fk 
                        FOREIGN KEY (therapist_id) REFERENCES users(id) ON DELETE CASCADE;
                END IF;
            END $$;

            -- Add scheduled_at column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='scheduled_at') THEN
                    ALTER TABLE telehealth_session ADD COLUMN scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
                END IF;
            END $$;

            -- Add duration column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='duration') THEN
                    ALTER TABLE telehealth_session ADD COLUMN duration INTEGER NOT NULL DEFAULT 30;
                END IF;
            END $$;

            -- Add status column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='status') THEN
                    ALTER TABLE telehealth_session ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'scheduled';
                END IF;
            END $$;

            -- Add session_url column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='session_url') THEN
                    ALTER TABLE telehealth_session ADD COLUMN session_url VARCHAR(200) NULL;
                END IF;
            END $$;

            -- Add room_id column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='room_id') THEN
                    ALTER TABLE telehealth_session ADD COLUMN room_id VARCHAR(255) NULL;
                END IF;
            END $$;

            -- Add notes column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='notes') THEN
                    ALTER TABLE telehealth_session ADD COLUMN notes TEXT NULL;
                END IF;
            END $$;

            -- Add has_recording column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='has_recording') THEN
                    ALTER TABLE telehealth_session ADD COLUMN has_recording BOOLEAN NOT NULL DEFAULT FALSE;
                END IF;
            END $$;

            -- Add has_transcript column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='has_transcript') THEN
                    ALTER TABLE telehealth_session ADD COLUMN has_transcript BOOLEAN NOT NULL DEFAULT FALSE;
                END IF;
            END $$;

            -- Add recording_url column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='recording_url') THEN
                    ALTER TABLE telehealth_session ADD COLUMN recording_url VARCHAR(200) NULL;
                END IF;
            END $$;

            -- Add transcript_url column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='transcript_url') THEN
                    ALTER TABLE telehealth_session ADD COLUMN transcript_url VARCHAR(200) NULL;
                END IF;
            END $$;

            -- Add created_at column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='created_at') THEN
                    ALTER TABLE telehealth_session ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
                END IF;
            END $$;

            -- Add updated_at column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='updated_at') THEN
                    ALTER TABLE telehealth_session ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
                END IF;
            END $$;

            -- Add started_at column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='started_at') THEN
                    ALTER TABLE telehealth_session ADD COLUMN started_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;
            END $$;

            -- Add ended_at column if not exists
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='telehealth_session' AND column_name='ended_at') THEN
                    ALTER TABLE telehealth_session ADD COLUMN ended_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;
            END $$;

            -- Create indexes if they don't exist
            CREATE INDEX IF NOT EXISTS telehealth_session_patient_id_idx ON telehealth_session(patient_id);
            CREATE INDEX IF NOT EXISTS telehealth_session_therapist_id_idx ON telehealth_session(therapist_id);
            CREATE INDEX IF NOT EXISTS telehealth_session_patient_status_idx ON telehealth_session(patient_id, status);
            CREATE INDEX IF NOT EXISTS telehealth_session_therapist_status_idx ON telehealth_session(therapist_id, status);
            CREATE INDEX IF NOT EXISTS telehealth_session_scheduled_at_idx ON telehealth_session(scheduled_at);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
