# Generated by Django 4.2.7 on 2026-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telehealth", "0003_allow_null_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="telehealthsession",
            name="is_emergency",
            field=models.BooleanField(
                default=False, help_text="Whether this is an emergency session"
            ),
        ),
    ]
