# Generated by Django 4.2.7 on 2026-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telehealth", "0004_telehealthsession_is_emergency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telehealthsession",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
