# Generated by Django 4.2.25 on 2025-11-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.TextField(help_text='Encrypted field', max_length=500)),
                ('last_name', models.TextField(help_text='Encrypted field', max_length=500)),
                ('middle_name', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('email', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('phone', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('phone_secondary', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('street_address', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('city', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('country', models.CharField(default='US', max_length=2)),
                ('ssn', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('medical_record_number', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('emergency_contact_name', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('emergency_contact_phone', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('emergency_contact_relationship', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, help_text='List of known allergies')),
                ('medical_conditions', models.TextField(blank=True, help_text='Current medical conditions')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('communication_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'permissions': [('view_patient_phi', 'Can view patient PHI'), ('edit_patient_phi', 'Can edit patient PHI'), ('delete_patient_phi', 'Can delete patient PHI')],
            },
        ),
        migrations.CreateModel(
            name='PatientTherapistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_therapist_assignments',
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('intake', 'Intake Form'), ('consent', 'Consent Form'), ('insurance', 'Insurance Card'), ('id', 'ID Verification'), ('medical', 'Medical Records'), ('lab', 'Lab Results'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Document',
                'verbose_name_plural': 'Patient Documents',
                'db_table': 'patient_documents',
                'permissions': [('view_patient_documents', 'Can view patient documents'), ('upload_patient_documents', 'Can upload patient documents'), ('delete_patient_documents', 'Can delete patient documents')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_therapists',
            field=models.ManyToManyField(related_name='assigned_patients', through='patients.PatientTherapistAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('primary', 'Primary Insurance'), ('secondary', 'Secondary Insurance'), ('tertiary', 'Tertiary Insurance')], default='primary', max_length=20)),
                ('provider_name', models.TextField(help_text='Encrypted field', max_length=500)),
                ('policy_number', models.TextField(help_text='Encrypted field', max_length=500)),
                ('group_number', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('subscriber_id', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('subscriber_name', models.TextField(blank=True, help_text='Encrypted field', max_length=500)),
                ('subscriber_dob', models.DateField(blank=True, null=True)),
                ('relationship_to_patient', models.CharField(default='self', max_length=20)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('copay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deductible_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Insurance Information',
                'verbose_name_plural': 'Insurance Information',
                'db_table': 'patient_insurance',
            },
        ),
        migrations.AddIndex(
            model_name='patienttherapistassignment',
            index=models.Index(fields=['patient', 'is_primary'], name='patient_the_patient_35a5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='patienttherapistassignment',
            index=models.Index(fields=['therapist', 'assigned_date'], name='patient_the_therapi_ef669f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttherapistassignment',
            unique_together={('patient', 'therapist', 'assigned_date')},
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(fields=['patient', 'document_type'], name='patient_doc_patient_eef291_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(fields=['is_active'], name='patient_doc_is_acti_cba090_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number'], name='patients_patient_dd5a30_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patients_status_7c14f6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['primary_therapist'], name='patients_primary_52a668_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['admission_date'], name='patients_admissi_34fece_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceinformation',
            index=models.Index(fields=['patient', 'insurance_type'], name='patient_ins_patient_b2ee7b_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceinformation',
            index=models.Index(fields=['is_active'], name='patient_ins_is_acti_d7e651_idx'),
        ),
    ]
