# Generated by Django 4.2.7 on 2026-02-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceinformation",
            name="group_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="insuranceinformation",
            name="policy_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="insuranceinformation",
            name="provider_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="insuranceinformation",
            name="subscriber_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="insuranceinformation",
            name="subscriber_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_record_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_secondary",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ssn",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="patient",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
