# Generated by Django 4.2.7 on 2026-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_insuranceinformation_group_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceinformation",
            name="provider_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="insuranceinformation",
            name="subscriber_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
