# Generated by Django 4.2.7 on 2026-01-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0002_alter_appointment_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOAPNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subjective",
                    models.TextField(
                        help_text="Patient's description of their condition, symptoms, feelings"
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="Observable, measurable data (vital signs, test results, observations)"
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        help_text="Professional diagnosis or clinical impression"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        help_text="Treatment plan, interventions, follow-up actions"
                    ),
                ),
                ("session_date", models.DateTimeField()),
                (
                    "session_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                ("chief_complaint", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("amended", "Amended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soap_notes",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soap_notes_as_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["therapist", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soap_notes_as_therapist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "soap_notes",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["patient", "session_date"],
                        name="soap_notes_patient_6e7c77_idx",
                    ),
                    models.Index(
                        fields=["therapist", "session_date"],
                        name="soap_notes_therapi_29ec53_idx",
                    ),
                    models.Index(
                        fields=["status"], name="soap_notes_status_6e1a69_idx"
                    ),
                ],
            },
        ),
    ]
